feat: update git script
This update only mounts required configurations for SSH and Git instead
of mounting the whole home directory. By mounting conditionally mounting
'/' for absolute arguments, git can now be used with absolute paths as
well.

diff --git a/git b/git
--- a/git
+++ b/git
@@ -2,41 +2,51 @@
 #
 # Wrapper script for git commands to run inside the Docker container.
 
-readonly container_name=${CONTAINER_NAME:-"git-command"}
+readonly container_workdir=/git
+readonly image_name="${IMAGE_NAME:-git-command}"
+readonly image_tag="${IMAGE_TAG:-latest}"
 
 # The user might have a custom alias or uses some other docker binary which
 # we do not want to override.
-if ! command -v docker &>/dev/null; then
-  docker_bin="$HOME/kodi/addons/service.system.docker/bin/docker"
-else
-  docker_bin="docker"
+docker_bin=$(command -v docker || echo "$HOME/.kodi/addons/service.system.docker/bin/docker")
+if [[ ! -x "$docker_bin" ]]; then
+  echo "docker binary not found or not executable" >&2
+  exit 1
 fi
 
-if [ -S "$SSH_AUTH_SOCK" ]; then
-  ssh_agent_mount="--volume $SSH_AUTH_SOCK:$SSH_AUTH_SOCK --env SSH_AUTH_SOCK=$SSH_AUTH_SOCK"
-else
-  ssh_agent_mount=""
+# Passthrough SSH_AUTH_SOCK if set on host.
+ssh_agent_mount=()
+if [[ -S "$SSH_AUTH_SOCK" ]]; then
+  ssh_agent_mount=(--volume "$SSH_AUTH_SOCK:$SSH_AUTH_SOCK" --env SSH_AUTH_SOCK="$SSH_AUTH_SOCK")
 fi
 
+# To support absolute paths, we must mount root '/' as working directory and
+# prepend it to the work directory within the container. Otherwise, we just
+# mount the current working directory (PWD) as working directory.
 args=()
-host_path=$PWD
-
+host_workdir=$PWD
 for arg in "$@"; do
   if [[ "$arg" == /* ]]; then
-    args+=("/git$arg")
-    host_path=/
+    args+=("$container_workdir$arg")
+    host_workdir=/
   else
     args+=("$arg")
   fi
 done
 
-# We also pass the user id and group id to the container to ensure that the user
-# has the same permissions inside the container as outside.
+# Mount additional SSH and Git configurations if available on host.
+config_volumes=()
+for path in .ssh .gitconfig .config/git; do
+  if [[ -f "$path" || -d "$path" ]]; then
+    config_volumes+=(--volume "$HOME/$path:/$path:ro")
+  fi
+done
+
 "$docker_bin" run --rm -it \
   --user "$(id -u):$(id -g)" \
-  --volume "$HOME":/root \
-  --volume "$host_path":/git \
-  --workdir /git \
+  --volume "$host_workdir":"$container_workdir" \
+  "${config_volumes[@]}" \
   "${ssh_agent_mount[@]}" \
-  "$container_name" \
+  --workdir "$container_workdir" \
+  "${image_name}:${image_tag}" \
   "${args[@]}"
